### ISSUE TITLE
Remove child home visit tasks [LMH]

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-client-chw#1089]
#### Tasks to remove
- [x] Remove the Minimum Dietary Diversity task in the child home visit
- [x] Remove the ECD task in the child home visit
- [x] Remove the Sleeping under a LLITN task in the child home visit
- Data dictionary link (child home visit tab): https://docs.google.com/spreadsheets/d/1yGuNHYoPq8OsjTPV4XiBj_FSNaQjIeVeNkKMe7SVKv8/edit#gid=1775888911 

#### Child profile updates
- [x] Update the child profile Upcoming Services page to reflect the task removals listed above
- [x] Update the child profile Medical History page to reflect the task removals listed above (i.e. remove sections for Minimum Dietary Diversity, ECD, Sleeping under a LLITN)
  <img src="https://user-images.githubusercontent.com/1584163/72229320-c32d5900-357b-11ea-80c1-18eb95318515.png" width="333">
- Note: Upcoming Services and Medical History also get updates from vaccine changes as listed in https://github.com/OpenSRP/opensrp-client-chw/issues/1088

**Comment by rowo** [comment]
@rkodev On the 17 Jan release, I still see ECD and LLITN and MDD in the history. I assume this is because the data exists. So when the data gets cleaned up for the research trip, will these disappear?

**Comment by AnnieMungai** [comment]
Version 0.0.1 (29th Jan 2020)
 
All not required has been removed and it reflects in child's history and upcoming services. 

It's good to go!
