### ISSUE TITLE
Fixes for the DRC release candidate

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw#1700]
DRC release candidate QA results:

- [x] 1. When you exit out of the Pregnancy Outcome form without saving, the user lands on the PNC register, when they should be landing on the woman's profile page from which they originally opened the form. **worked on by** @rkodev 

~~2. Completed tasks disappear from the ANC home visit when you re-open it to edit it, for e.g. ANC card, Delivery kit (DRC only), TT, SP, Obs & Illness tasks no longer appear. Is this related to editing LMP/EDD? If so, we can try to turn off the setting. **worked on by** @qaziabubakar /@rkodev~~ **Moved to https://github.com/OpenSRP/opensrp-client-chw/issues/1710**

- [x] 3. App closes when you exit out of the ANC visit page without saving (doesn't crash, but just closes). See ANC woman "Monica Bing". Open the ANC visit from the register list page, not the woman's profile page. worked on by @rkodev 
- [ ] 4. App reverts to English once you submit a family registration form **worked on by** @rkodev 
- [x] 5. Seems like the Obs & Illness task doesn't appear if you register a woman less than 13 weeks pregnant (I registered a woman as 8 weeks pregnant and the task doesn't appear) **worked on by** @qaziabubakar / @rkodev 

~~6. A few child tasks disappear when you re-open the child home visit to make edits (similar to what's happening during ANC home visit - is this related to the editing configuration we've enabled?) **worked on by** @rkodev~~ **Moved to https://github.com/OpenSRP/opensrp-client-chw/issues/1710**

- [x] 7. In the pregnancy outcome form, the live birth repeat group automation isn't working anymore. Instead of automatically creating the repeat groups, the user again has to check the checkmark. **worked on by** @qaziabubakar 
- [x] 8. PHYSICALLY CHALLENGED label below the child's name is not in French. See this issue: https://github.com/OpenSRP/opensrp-client-chw/issues/1427. The key string for this was translated in Transifex, so  might just need to be pulled in. **worked on by** @qaziabubakar 
- [x] 9. Women up to date with their PNC health facility visits indicator label is still in English.  See this issue: https://github.com/OpenSRP/opensrp-client-chw/issues/1346#issuecomment-762617049. The translation is added in Transifex, so probably just needs to be pulled in. **worked on by** @qaziabubakar 
- [ ] 10. https://github.com/OpenSRP/opensrp-client-chw/issues/1682 **worked on by** @qaziabubakar 
- [x] 11. https://github.com/OpenSRP/opensrp-client-chw/issues/1648 **worked on by** @rkodev

**Comment by rkodev** [comment]
@cafootitt Issue (2) is tied to submitting a visit immediately after saving. Disabling the feature will help as we might require some time to debug

**Comment by cafootitt** [comment]
Let's disable the feature for now then.

**Comment by cafootitt** [comment]
- [ ] 1
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 7
- [ ] 8
- [ ] 9
