### ISSUE TITLE
List of Items that needs review and rethinking 

### ISSUE THREAD

**Issue by ageryck** [opensrp/opensrp-client-chw#1907]
- [ ] Indicating last sync datetime on the newly implemented sync progress bar
- [ ] Show/tag each register individual  records with a synced mark (either color coding or small green check), aim is to identify which exact record hasn't synced
- [ ] Ability to show on the client app the records on device per user/location, this for devices holding records for more than one provider either correctly or erroneously out of wrong team assignment 
- [ ] Implement additional sync stats indicators as scoped on sync progress bar issue, need to make it configurable for brief view vs long list of all events

**Comment by allan-on** [comment]
> @allan-on we can execute the first issue as we rethink the rest to be scoped better scoping

@ageryck Great. Here's the [Add last sync date-time in addition to the sync progress bar](https://github.com/opensrp/opensrp-client-chw/issues/1944) issue I created. 
We first need to figure out where that detail will be rendered on the nav drawer. We might need some input from @rowo on that
