### ISSUE TITLE
Implement the Child Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#497]
<img width="379" alt="Picture3" src="https://user-images.githubusercontent.com/20777928/61238514-7809c900-a745-11e9-95bb-177201c6ad35.png">

- [x] All clients in the Child register will appear in this register.
- [x] Top left menu button opens side menu (#502  )
- [x] Swiping from the left also opens side menu (#502 )
- [x] Dynamic search bar (#544)
- [x] Due only toggle (#519 )
- [x] Row text display - first line: CG: {first_name} {middle_name} {surname} - This would be of the primary caregiver info for the family taken from the Registration information.
- [x] Row text display - second line: {first_name} (middle_name} {surname}, {age} - This would be the child U5 information taken from Registration Info
- [x] Row text display - third line: Child {sex} {fam_village} - Taken from the Registration Info.
- [ ] Row text display - fourth line: (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Susan as an example.
- [x] Client row arrow takes you to the client's profile

**Comment by msschroeder** [comment]
QA 16 August Build:
- [ ]  Switch Row text display to - third line: {sex} {fam_village} - Taken from the Registration Info.

**Comment by ellykits** [comment]
Closing this the remaining referral row can be tracked here #760

**Comment by msschroeder** [comment]
lgtm - create a new issue for the due filter for referral
