### ISSUE TITLE
Implement ANC register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#498]
<img width="379" alt="Picture3" src="https://user-images.githubusercontent.com/20777928/61238693-d9ca3300-a745-11e9-97f1-a35adb9faa9f.png">

- [x] All clients in the ANC register will appear in this register.
- [x] Top left menu button opens side menu (#502 )
- [x] Swiping from the left also opens side menu (#502 )
- [x] Dynamic search bar (#544 3)
- [x] Due only toggle (#519 )
- [x] Row text display - first line: {first_name} {middle_name} {surname}, {age} - Taken from the Registration information.
- [x] Row text display - second line: , GA: {gest_age} weeks {fam_village} - Taken from Registration Info and ANC registration information
- [ ] Row text display - third line: (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Susan as an example.
- [x] Client row arrow takes you to the client's profile

**Comment by msschroeder** [comment]
QA Sept 1 Build:
I will close this issue and create a new issue for the remaining part with the referral row part.

**Comment by ellykits** [comment]
@msschroeder I have created an issues for tracking the remaining referral row on major registers on HF. Follow the issue here ==> #760

**Comment by msschroeder** [comment]
I created a new issue for the due filter.
