### ISSUE TITLE
Implement PNC register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#499]
<img width="379" alt="Picture3" src="https://user-images.githubusercontent.com/20777928/61238920-5bba5c00-a746-11e9-82de-693866a2764d.png">

- [ ] All clients in the PNC register will appear in this register.
- [ ] Top left menu button opens side menu (#2 )
- [ ] Swiping from the left also opens side menu (#2)
- [ ] Dynamic search bar (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/3)
- [ ] Due only toggle (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/27)
- [ ] Row text display - first line: {first_name} {middle_name} {surname}, {age} - Taken from the Registration information.
- [ ] Row text display - second line: PNC day [{today} -{delivery_date}] {fam_village} - Taken from Registration Info and ANC registration information
- [ ] Row text display - third line: (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Susan as an example.
- [ ] Client row arrow takes you to the client's profile

**Comment by msschroeder** [comment]
QA Sept 20th: I have not been able to QA the referral component for the PNC as you cannot yet refer for PNC. I will wait to close once that is approved
