### ISSUE TITLE
Implement Malaria Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#500]
<img width="379" alt="Picture3" src="https://user-images.githubusercontent.com/20777928/61239203-1185aa80-a747-11e9-81b4-34f5a4f68cee.png">

- [ ] All clients in the Malaria register will appear in this register.
- [ ] Top left menu button opens side menu (#2 )
- [ ] Swiping from the left also opens side menu (#2)
- [ ] Dynamic search bar (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/3)
- [ ] Due only toggle (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/27)
- [ ] Row text display - first line: {first_name} {middle_name} {surname}, {age} - Taken from the Registration information.
- [ ] Row text display - second line: {sex} {fam_village} - Taken from Registration Info.
- [ ] Row text display - third line: (if the client has a referral): Referral [number of days since referral is given] days ago - This should be red text with a light red background as shown in the screen shot above with Susan as an example.
- [ ] Client row arrow takes you to the client's profile
