### ISSUE TITLE
Implement the All Families Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#505]
Similar as the [CHW All Families Register](https://github.com/OpenSRP/opensrp-client-chw/issues/8). I have copied the issue here for simplicity and added some slight changes

Marvel prototype: https://marvelapp.com/9j1277a/screen/48411528 (with alterations not included in prototype. Please see screen shot below too.

<img width="304" alt="Screen_Shot_2019-07-21_at_7_45_39_AM" src="https://user-images.githubusercontent.com/20777928/61587079-b6f7ae80-ab8b-11e9-86d5-f68b3411a06a.png">

- [x] Top left menu button opens side menu (#502  )
- [x] Swiping from the left also opens side menu (#502 )
- [x] Dynamic search bar (https://github.com/OpenSRP/opensrp-client-chw/issues/492)
- [x] Please change the text in the dynamic search to read "Search name or ID"
- [x] NO due only toggle will be included. (#503 )
- [x] NO Family Services (#503 )
- [x] Row shows "{fam_name} Family" from Family Registration form
- [x] Implement icons for each female, male child, pregnant mother, PNC mother/child, and malaria case.  I will post a link to the icons in the issue. (https://github.com/OpenSRP/opensrp-client-chw/issues/504)
- [x] Where you see "Lavington #445", use the {fam_village} from the Family Registration form
- [x] Home button at the bottom takes the user back to the main register page for whichever register they're currently in.
- [x] Scan QR needs to be configurable - it should be an option, but has not been discussed for implementation. They have not provided the logistics for using QR codes, but it should be shown in the bottom navigation menu.
- [x] Add family opens the add family registration form (issue to be created)

**Comment by mberg** [comment]
Most of these links in the issues don't work @msschroeder

**Comment by msschroeder** [comment]
lgtm
