### ISSUE TITLE
Implement Family Profile page - Members tab

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#508]
Same as the [CHW All Families Register](https://github.com/OpenSRP/opensrp-client-chw/issues/21). I have copied the issue here for simplicity.

Marvel: https://marvelapp.com/9j1277a/screen/48411529

<img width="376" alt="screen shot 2018-12-05 at 11 23 33 pm" src="https://user-images.githubusercontent.com/1584163/49561347-cff56d00-f8e4-11e8-81c8-e7fbfae256e0.png">

- [x] This is the page you land on when you tap on a family record row in the family register list
- [x] "Return to All Families" goes back to family register list 
- [x] {fam_name} Family, then {fam_village} from Family Registration form
- [x] No Due tab (#526 )
- [x] No Activity tab (#527)
- [x] Members tab lists all family members, from oldest to youngest, followed by any deceased members
- [x] Deceased members are shown at the bottom of the list, in lighter grey, italic font (see mockup)
- [x] For deceased members, if they previously had a profile picture, remove the picture and switch back to the avatar
- [x] Age shown for the deceased is the age at which they died
- [x] For each member, show their {first_name} {middle_name} {last_name} followed by age and sex
- [x] The head of family and primary caregiver statuses are shown below, if applicable.
- [x] For all living family members, the right arrow takes you to the member's profile page
- [x] FAB and Top Right Drop-down (https://github.com/OpenSRP/opensrp-client-chw/issues/507)

**Comment by msschroeder** [comment]
@ellykits Please note, I deleted one of the tick boxes as it didn't make sense. It was related to the home visits in the CHW app.

**Comment by msschroeder** [comment]
lgtm
