### ISSUE TITLE
Implement the All Client Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#518]
![Picture2](https://user-images.githubusercontent.com/20777928/61236326-696ce300-a740-11e9-9bbc-4a60f276d909.png)

- [ ] All clients with a referral or in another register (i.e. ANC, Malaria, PNC, Family Planning) will appear in this register
- [ ] Top left menu button opens side menu (#2 )
- [ ] Swiping from the left also opens side menu (#2)
- [ ] Dynamic search bar (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/3)
- [ ] Due only toggle (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/25)
- [ ] Row text display (https://github.com/OpenSRP/opensrp-client-chw-hf/issues/24)
- [ ] Client row arrow takes you to the client's profile
