### ISSUE TITLE
Implement the Referrals Register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw#562]
<img width="379" alt="referralregister" src="https://user-images.githubusercontent.com/20777928/62136048-048ebc80-b2ec-11e9-859d-a115663e68c9.png">

- [x] Top left menu button opens side menu (#502  )
- [x] Swiping from the left also opens side menu (#502 )
- [x] Dynamic search bar (#544 )
- [x] NO Due only toggle button
- [x] Row text display will be dependent on the type of referral made. The content can be referenced in the [referral data dictionary](https://docs.google.com/spreadsheets/d/1uPwajfoBnMrM6NYUyMeFATFQwSisqb8kfGXUG3nySyI/edit?usp=sharing), tab Referrals, Column "Brief Referral HF Receives".
- [x] Clicking on a client row takes you to detailed referral (#560 )
- [x] Referrals are shown from the most recent at the top and oldest at the bottom. 
- [x] The date or time today the referral was made appear on the far right of the client referral row (as shown in the mock-up)
- [x] Search box text should display, "Search name or id" as in other register, but not shown in mock-up above,

**Comment by msschroeder** [comment]
@githengi @dubdabasoduba Right now the referrals flow from the referral register to the profile. I see this issue related to this has not yet been done. Are we in the process of fixing this or are you planning on keeping it as is?

**Comment by githengi** [comment]
@msschroeder I have ticked the issue to done. This was done its just that it was not ticked.

**Comment by msschroeder** [comment]
@githengi The only think is the the referral register should go to the detailed view and this is not occurring right now. So I will just flag this as an issue

**Comment by msschroeder** [comment]
QA 16th August Build:
- [ ] When you click the arrow from the referral page next to a referral, it should go to the detailed referral view.

**Comment by msschroeder** [comment]
QA Build August 27th:
- [ ] Change "Find name or ID" in the search box to "Search name or ID"

**Comment by msschroeder** [comment]
lgtm
