### ISSUE TITLE
Fix QA bugs for HF app for release v1.2.1

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-client-chw#759]

**Comment by ellykits** [comment]
Has bug fixes mentioned in the following issues: 

- [x] OpenSRP/opensrp-client-chw#562 - Referral register (Rename search bar field)
- [x] OpenSRP/opensrp-client-chw#727 - Remove answer from the pre-referral treatment on Problems field (ANC referral details)
- [x] OpenSRP/opensrp-client-chw#561 - Fix issues on close referral (change mark as done text to **mark done**)
- [ ] OpenSRP/opensrp-client-chw#511 - Fix missing family last name on call widget

**Comment by msschroeder** [comment]
OpenSRP/opensrp-client-chw#562 , OpenSRP/opensrp-client-chw#727 , and OpenSRP/opensrp-client-chw#561 lgtm
